### ISSUE TITLE
Instructions to build on Fedora

### ISSUE THREAD

**Issue by jayvdb** [huggle/huggle3-qt-lx#185]
There are wiki pages for installing on Windows and mac OS.

And the README (and files in `travis/`) covers Ubuntu.

A wiki page for building/ installing on Fedora would be helpful.

For example, one problem I found was that it defaults to installing into `/usr/local/`, and `/usr/local/lib` is not in the library cache, so huggle fails with a linker error.

To fix this, the following will add the libs, and then rebuild the cache.
```
echo /usr/local/lib | sudo tee /etc/ld.so.conf.d/usr-local-lib.conf
sudo ldconfig
```

**Comment by benapetr** [comment]
Putting it all together is not easy this is something where Windows beat Linux: it would be far more simple to properly build and package if every linux distro wasn't so much different from others.

You also need to get compiled extension so files to folder where Huggle finds them, otherwise you will be missing many features.

**Comment by benapetr** [comment]
BTW you could probably build it on Fedora easily just by getting Qt. You can download even official packages from internet and use ./configure --qtpath <path to qt> to compile it

**Comment by benapetr** [comment]
https://github.com/huggle/huggle3-qt-lx/wiki/Building-on-Linux
