### ISSUE TITLE
Do not install yaml-cpp globally

### ISSUE THREAD

**Issue by Hello71** [huggle/huggle3-qt-lx#277]
this is extremely bad.

**Comment by benapetr** [comment]
I have no idea what you talk about

**Comment by benapetr** [comment]
why it is not good?

**Comment by benapetr** [comment]
if you don't want to install huggle globally that don't run sudo make install, if you want to use it just yourself then keep it in huggle_release folder.

Installing binaries and libraries to /usr/local/ when running make install is a very common practice

**Comment by benapetr** [comment]
But we are talking about LINUX here not WINDOWS, so why you talk about some "DLL" hell or whatever. Packages installed with package manager install to /usr/lib packages installed by hand over sudo make install, go to /usr/local/lib

This has been a standard in GNU/Linux for decades. There is nothing wrong about it, and if some other app is using yaml-cpp library and is installed by hand as well using sudo make install, it will most likely work as well, since Huggle is shipping latest yaml-cpp library.

If you don't want it to affect global paths, then use snapcraft package which will be installed to container. Or don't install it system wide.

This is absolutely correct way to deploy software and everyone else does it as well.

**Comment by timawesomeness** [comment]
> Packages installed with package manager install to /usr/lib packages installed by hand over sudo make install, go to /usr/local/lib [...] If you don't want it to affect global paths, then use snapcraft package which will be installed to container. Or don't install it system wide.

Have you considered the possibility that someone might want to package huggle (which is the point of this issue) and install it through a package manager, thus installing it system wide?

Like Hello71 said, either check for and use system-wide libraries like you're supposed to, or force static linking with embedded libraries and don't install their headers system-wide. It's the responsibility of the package manager (or user, if there's no package manager) to install dependencies, not the program, regardless of where it's installed to.

I have never seen another program (at least not a C++ one) that bundles dependencies like this; this is very much not the correct way to deploy software on linux and nobody does it. People install dependencies, then install the program that depends on them.

**Comment by benapetr** [comment]
Well, I don't mind reopening this if there is a feasible solution. But keep in mind that Huggle is using yaml-cpp as a git submodule, and this is probably only way how vendor of yaml-cpp support its bundling via cmake to other projects.

Setup of Huggle is supposed to be hassle-free and therefore shouldn't rely on any other 3rd packages than cmake and Qt5. Everything else is bundled together with Huggle for easy setup.

yaml-cpp might be packaged for /some/ distributions, but I doubt it is for all of them. If there is any cmake switch that disables bundling of header files, which are indeed unnecessary, then I am happy to use, but I don't think so, so you might consider creating a PR in yaml-cpp repository which implements such a switch.

**Comment by benapetr** [comment]
btw any pull request that "fixes" this problem while still preserving the yaml-cpp library bundled as a git submodule for easy install is welcome, saying that something is wrong is easy, saying how it actually can be fixed is much harder, and nobody came with a useful solution proposal so far.
