### ISSUE TITLE
continuous integration is broken

### ISSUE THREAD

**Issue by NovemLinguae** [huggle/huggle3-qt-lx#355]
Doesn't look like it's passed since 0f390bb5451b3682bf321b2b8ffb0bf0730d448b in March 2022. Looks like there's something wrong with the Windows 2016 tests. Looks like they time out without running.

![image](https://user-images.githubusercontent.com/79697282/215657978-3f02288c-f02f-4f09-a751-ba5de635db21.png)

**Comment by phuzion** [comment]
I am aware of the issue. Ultimately, the proper solution is to update Huggle to build on the latest Visual Studio and Windows 2022, but in the meantime, I will submit a PR to remove Windows 2016 since [it was taken out of rotation in March of 2022.](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/)
